export enum ActionTypes {
  MOVE_CELL = "MOVE_CELL",
  DELETE_CELL = "DELETE_CELL",
  INSER_CELL_AFTER = "INSER_CELL_AFTER",
  UPDATE_CELL = "UPDATE_CELL",
  BUNDLE_START = "BUNDLE_START",
  BUNDLE_COMPLETE = "BUNDLE_COMPLETE",
}
